version: "3.3"
services:
    app:
        image: scheduling-app:${TAG-latest}
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            - PORT=${PORT}
        ports:
            - ${PORT}:${PORT}
